---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/wall.beyincikisleri.co/
    # Eğer alt klasöre kuruyorsanız yukarıdaki yolu değiştirin. Örn: /home/$USER/public_html/admin/
    - /bin/cp -R dist/* $DEPLOYPATH